### ISSUE TITLE
JDK14这个报错什么原因，怎样解决。

### ISSUE THREAD

**Issue by X-SMZX** [ExpLangcn/InfoSearchAll#4]
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error
umRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstan
.java:280)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(Quant
)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:2
        at com.sun.javafx.application.PlatformImpl.startup(Pla
)
        at com.sun.javafx.application.PlatformImpl.startup(Pla
)
        at com.sun.javafx.application.LauncherImpl.startToolki
a:658)
        at com.sun.javafx.application.LauncherImpl.launchAppli
pl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$laun
uncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.RuntimeException: Error initializing Quan
itable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineR
umRenderer.java:94)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineR
mRenderer.java:124)
        ... 1 more
Exception in thread "main" java.lang.RuntimeException: No tool
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:2
        at com.sun.javafx.application.PlatformImpl.startup(Pla
)
        at com.sun.javafx.application.PlatformImpl.startup(Pla
)
        at com.sun.javafx.application.LauncherImpl.startToolki
a:658)
        at com.sun.javafx.application.LauncherImpl.launchAppli
pl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$laun
uncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by ExpLangcn** [comment]
你自己的JDK版本是14嘛？

**Comment by X-SMZX** [comment]
> 你自己的JDK版本是14嘛？
是的
C:\Users\Administrator>java -version
java version "14.0.2" 2020-07-14
Java(TM) SE Runtime Environment (build 14.0.2+12-46)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)

**Comment by ExpLangcn** [comment]
我也不知道 抱歉
